#pragma once

// Generated from specs/sui-sign-transaction-policy-contract.tsv.
// Do not edit by hand. Run npm run generate:sui-policy-contract.

static_assert(
    kSuiPolicyFactMaxCommands == 8,
    "Sui policy command field count must match the shared policy contract");
static_assert(
    kSuiPolicyFactMaxTypeArguments == 4,
    "Sui policy MoveCall type-argument field count must match the shared policy contract");

constexpr const char* kCommandKindFields[kSuiPolicyFactMaxCommands] = {
    "sui.command0_kind",
    "sui.command1_kind",
    "sui.command2_kind",
    "sui.command3_kind",
    "sui.command4_kind",
    "sui.command5_kind",
    "sui.command6_kind",
    "sui.command7_kind",
};

constexpr const char* kCommandMoveCallPackageFields[kSuiPolicyFactMaxCommands] = {
    "sui.command0_move_call_package",
    "sui.command1_move_call_package",
    "sui.command2_move_call_package",
    "sui.command3_move_call_package",
    "sui.command4_move_call_package",
    "sui.command5_move_call_package",
    "sui.command6_move_call_package",
    "sui.command7_move_call_package",
};

constexpr const char* kCommandMoveCallModuleFields[kSuiPolicyFactMaxCommands] = {
    "sui.command0_move_call_module",
    "sui.command1_move_call_module",
    "sui.command2_move_call_module",
    "sui.command3_move_call_module",
    "sui.command4_move_call_module",
    "sui.command5_move_call_module",
    "sui.command6_move_call_module",
    "sui.command7_move_call_module",
};

constexpr const char* kCommandMoveCallFunctionFields[kSuiPolicyFactMaxCommands] = {
    "sui.command0_move_call_function",
    "sui.command1_move_call_function",
    "sui.command2_move_call_function",
    "sui.command3_move_call_function",
    "sui.command4_move_call_function",
    "sui.command5_move_call_function",
    "sui.command6_move_call_function",
    "sui.command7_move_call_function",
};

constexpr const char* kCommandMoveCallTypeArgCountFields[kSuiPolicyFactMaxCommands] = {
    "sui.command0_move_call_type_args",
    "sui.command1_move_call_type_args",
    "sui.command2_move_call_type_args",
    "sui.command3_move_call_type_args",
    "sui.command4_move_call_type_args",
    "sui.command5_move_call_type_args",
    "sui.command6_move_call_type_args",
    "sui.command7_move_call_type_args",
};

constexpr const char* kCommandMoveCallTypeArgFields
    [kSuiPolicyFactMaxCommands][kSuiPolicyFactMaxTypeArguments] = {
        {
            "sui.command0_move_call_type_arg0",
            "sui.command0_move_call_type_arg1",
            "sui.command0_move_call_type_arg2",
            "sui.command0_move_call_type_arg3",
        },
        {
            "sui.command1_move_call_type_arg0",
            "sui.command1_move_call_type_arg1",
            "sui.command1_move_call_type_arg2",
            "sui.command1_move_call_type_arg3",
        },
        {
            "sui.command2_move_call_type_arg0",
            "sui.command2_move_call_type_arg1",
            "sui.command2_move_call_type_arg2",
            "sui.command2_move_call_type_arg3",
        },
        {
            "sui.command3_move_call_type_arg0",
            "sui.command3_move_call_type_arg1",
            "sui.command3_move_call_type_arg2",
            "sui.command3_move_call_type_arg3",
        },
        {
            "sui.command4_move_call_type_arg0",
            "sui.command4_move_call_type_arg1",
            "sui.command4_move_call_type_arg2",
            "sui.command4_move_call_type_arg3",
        },
        {
            "sui.command5_move_call_type_arg0",
            "sui.command5_move_call_type_arg1",
            "sui.command5_move_call_type_arg2",
            "sui.command5_move_call_type_arg3",
        },
        {
            "sui.command6_move_call_type_arg0",
            "sui.command6_move_call_type_arg1",
            "sui.command6_move_call_type_arg2",
            "sui.command6_move_call_type_arg3",
        },
        {
            "sui.command7_move_call_type_arg0",
            "sui.command7_move_call_type_arg1",
            "sui.command7_move_call_type_arg2",
            "sui.command7_move_call_type_arg3",
        },
    };


constexpr AgentQPolicyFieldDescriptor kSuiSignTransactionPolicyFields[] = {
    {"sui.transaction_kind", AgentQPolicyValueType::string, true, true, false},
    {"sui.sender_address", AgentQPolicyValueType::string, true, true, false},
    {"sui.gas_owner_address", AgentQPolicyValueType::string, true, true, false},
    {"sui.command_count", AgentQPolicyValueType::u64_decimal, true, false, true},
    {"sui.gas_budget", AgentQPolicyValueType::u64_decimal, true, false, true},
    {"sui.gas_price", AgentQPolicyValueType::u64_decimal, true, false, true},
    {"sui.expiration_kind", AgentQPolicyValueType::string, true, true, false},
    {"sui.sui_total_out_complete", AgentQPolicyValueType::string, true, false, false},
    {"sui.sui_total_out_raw", AgentQPolicyValueType::u64_decimal, true, true, true},
    {"sui.transfer_total_out_raw", AgentQPolicyValueType::u64_decimal, true, true, true},
    {"sui.move_call_total_in_raw", AgentQPolicyValueType::u64_decimal, true, true, true},
    {"sui.recipient_count", AgentQPolicyValueType::u64_decimal, true, true, true},
    {"sui.recipient0_address", AgentQPolicyValueType::string, true, true, false},
    {"sui.recipient0_amount_raw", AgentQPolicyValueType::u64_decimal, true, true, true},
    {"sui.move_call0_package", AgentQPolicyValueType::string, true, true, false},
    {"sui.move_call0_module", AgentQPolicyValueType::string, true, true, false},
    {"sui.move_call0_function", AgentQPolicyValueType::string, true, true, false},
    {"sui.move_call0_sui_amount_raw", AgentQPolicyValueType::u64_decimal, true, true, true},
    {"sui.coin_flow0_source_kind", AgentQPolicyValueType::string, true, true, false},
    {"sui.coin_flow0_asset_state", AgentQPolicyValueType::string, true, true, false},
    {"sui.coin_flow0_amount_known", AgentQPolicyValueType::string, true, false, false},
    {"sui.coin_flow0_amount_raw", AgentQPolicyValueType::u64_decimal, true, true, true},
    {"sui.coin_flow0_sink_kind", AgentQPolicyValueType::string, true, true, false},
    {"sui.coin_flow0_object_id", AgentQPolicyValueType::string, true, true, false},
    {"sui.command0_kind", AgentQPolicyValueType::string, true, true, false},
    {"sui.command1_kind", AgentQPolicyValueType::string, true, true, false},
    {"sui.command2_kind", AgentQPolicyValueType::string, true, true, false},
    {"sui.command3_kind", AgentQPolicyValueType::string, true, true, false},
    {"sui.command4_kind", AgentQPolicyValueType::string, true, true, false},
    {"sui.command5_kind", AgentQPolicyValueType::string, true, true, false},
    {"sui.command6_kind", AgentQPolicyValueType::string, true, true, false},
    {"sui.command7_kind", AgentQPolicyValueType::string, true, true, false},
    {"sui.command0_move_call_package", AgentQPolicyValueType::string, true, true, false},
    {"sui.command1_move_call_package", AgentQPolicyValueType::string, true, true, false},
    {"sui.command2_move_call_package", AgentQPolicyValueType::string, true, true, false},
    {"sui.command3_move_call_package", AgentQPolicyValueType::string, true, true, false},
    {"sui.command4_move_call_package", AgentQPolicyValueType::string, true, true, false},
    {"sui.command5_move_call_package", AgentQPolicyValueType::string, true, true, false},
    {"sui.command6_move_call_package", AgentQPolicyValueType::string, true, true, false},
    {"sui.command7_move_call_package", AgentQPolicyValueType::string, true, true, false},
    {"sui.command0_move_call_module", AgentQPolicyValueType::string, true, true, false},
    {"sui.command1_move_call_module", AgentQPolicyValueType::string, true, true, false},
    {"sui.command2_move_call_module", AgentQPolicyValueType::string, true, true, false},
    {"sui.command3_move_call_module", AgentQPolicyValueType::string, true, true, false},
    {"sui.command4_move_call_module", AgentQPolicyValueType::string, true, true, false},
    {"sui.command5_move_call_module", AgentQPolicyValueType::string, true, true, false},
    {"sui.command6_move_call_module", AgentQPolicyValueType::string, true, true, false},
    {"sui.command7_move_call_module", AgentQPolicyValueType::string, true, true, false},
    {"sui.command0_move_call_function", AgentQPolicyValueType::string, true, true, false},
    {"sui.command1_move_call_function", AgentQPolicyValueType::string, true, true, false},
    {"sui.command2_move_call_function", AgentQPolicyValueType::string, true, true, false},
    {"sui.command3_move_call_function", AgentQPolicyValueType::string, true, true, false},
    {"sui.command4_move_call_function", AgentQPolicyValueType::string, true, true, false},
    {"sui.command5_move_call_function", AgentQPolicyValueType::string, true, true, false},
    {"sui.command6_move_call_function", AgentQPolicyValueType::string, true, true, false},
    {"sui.command7_move_call_function", AgentQPolicyValueType::string, true, true, false},
    {"sui.command0_move_call_type_args", AgentQPolicyValueType::u64_decimal, true, false, true},
    {"sui.command1_move_call_type_args", AgentQPolicyValueType::u64_decimal, true, false, true},
    {"sui.command2_move_call_type_args", AgentQPolicyValueType::u64_decimal, true, false, true},
    {"sui.command3_move_call_type_args", AgentQPolicyValueType::u64_decimal, true, false, true},
    {"sui.command4_move_call_type_args", AgentQPolicyValueType::u64_decimal, true, false, true},
    {"sui.command5_move_call_type_args", AgentQPolicyValueType::u64_decimal, true, false, true},
    {"sui.command6_move_call_type_args", AgentQPolicyValueType::u64_decimal, true, false, true},
    {"sui.command7_move_call_type_args", AgentQPolicyValueType::u64_decimal, true, false, true},
    {"sui.command0_move_call_type_arg0", AgentQPolicyValueType::string, true, true, false},
    {"sui.command0_move_call_type_arg1", AgentQPolicyValueType::string, true, true, false},
    {"sui.command0_move_call_type_arg2", AgentQPolicyValueType::string, true, true, false},
    {"sui.command0_move_call_type_arg3", AgentQPolicyValueType::string, true, true, false},
    {"sui.command1_move_call_type_arg0", AgentQPolicyValueType::string, true, true, false},
    {"sui.command1_move_call_type_arg1", AgentQPolicyValueType::string, true, true, false},
    {"sui.command1_move_call_type_arg2", AgentQPolicyValueType::string, true, true, false},
    {"sui.command1_move_call_type_arg3", AgentQPolicyValueType::string, true, true, false},
    {"sui.command2_move_call_type_arg0", AgentQPolicyValueType::string, true, true, false},
    {"sui.command2_move_call_type_arg1", AgentQPolicyValueType::string, true, true, false},
    {"sui.command2_move_call_type_arg2", AgentQPolicyValueType::string, true, true, false},
    {"sui.command2_move_call_type_arg3", AgentQPolicyValueType::string, true, true, false},
    {"sui.command3_move_call_type_arg0", AgentQPolicyValueType::string, true, true, false},
    {"sui.command3_move_call_type_arg1", AgentQPolicyValueType::string, true, true, false},
    {"sui.command3_move_call_type_arg2", AgentQPolicyValueType::string, true, true, false},
    {"sui.command3_move_call_type_arg3", AgentQPolicyValueType::string, true, true, false},
    {"sui.command4_move_call_type_arg0", AgentQPolicyValueType::string, true, true, false},
    {"sui.command4_move_call_type_arg1", AgentQPolicyValueType::string, true, true, false},
    {"sui.command4_move_call_type_arg2", AgentQPolicyValueType::string, true, true, false},
    {"sui.command4_move_call_type_arg3", AgentQPolicyValueType::string, true, true, false},
    {"sui.command5_move_call_type_arg0", AgentQPolicyValueType::string, true, true, false},
    {"sui.command5_move_call_type_arg1", AgentQPolicyValueType::string, true, true, false},
    {"sui.command5_move_call_type_arg2", AgentQPolicyValueType::string, true, true, false},
    {"sui.command5_move_call_type_arg3", AgentQPolicyValueType::string, true, true, false},
    {"sui.command6_move_call_type_arg0", AgentQPolicyValueType::string, true, true, false},
    {"sui.command6_move_call_type_arg1", AgentQPolicyValueType::string, true, true, false},
    {"sui.command6_move_call_type_arg2", AgentQPolicyValueType::string, true, true, false},
    {"sui.command6_move_call_type_arg3", AgentQPolicyValueType::string, true, true, false},
    {"sui.command7_move_call_type_arg0", AgentQPolicyValueType::string, true, true, false},
    {"sui.command7_move_call_type_arg1", AgentQPolicyValueType::string, true, true, false},
    {"sui.command7_move_call_type_arg2", AgentQPolicyValueType::string, true, true, false},
    {"sui.command7_move_call_type_arg3", AgentQPolicyValueType::string, true, true, false},
};

static_assert(
    sizeof(kSuiSignTransactionPolicyFields) / sizeof(kSuiSignTransactionPolicyFields[0]) <=
        kAgentQPolicyMaxFieldDescriptors,
    "Sui sign_transaction policy descriptor count exceeds policy capacity");

constexpr SuiRequiredSignBound kSuiSignTransactionRequiredSignBounds[] = {
    {SuiRequiredSignBoundKind::eq, "common.chain", "sui"},
    {SuiRequiredSignBoundKind::eq, "common.method", "sign_transaction"},
    {SuiRequiredSignBoundKind::eq, "common.intent", "programmable_transaction"},
    {SuiRequiredSignBoundKind::eq, "sui.transaction_kind", "programmable_transaction"},
    {SuiRequiredSignBoundKind::string, "sui.sender_address", nullptr},
    {SuiRequiredSignBoundKind::string, "sui.gas_owner_address", nullptr},
    {SuiRequiredSignBoundKind::lte, "sui.gas_budget", nullptr},
    {SuiRequiredSignBoundKind::lte, "sui.gas_price", nullptr},
    {SuiRequiredSignBoundKind::string, "sui.expiration_kind", nullptr},
    {SuiRequiredSignBoundKind::eq, "sui.sui_total_out_complete", "yes"},
    {SuiRequiredSignBoundKind::lte, "sui.sui_total_out_raw", nullptr},
    {SuiRequiredSignBoundKind::eq, "sui.command_count", "2"},
    {SuiRequiredSignBoundKind::eq, "sui.command0_kind", "split_coins"},
    {SuiRequiredSignBoundKind::eq, "sui.command1_kind", "transfer_objects"},
    {SuiRequiredSignBoundKind::eq, "sui.recipient_count", "1"},
    {SuiRequiredSignBoundKind::string_eq, "sui.recipient0_address", nullptr},
    {SuiRequiredSignBoundKind::lte, "sui.recipient0_amount_raw", nullptr},
    {SuiRequiredSignBoundKind::eq, "sui.coin_flow0_source_kind", "split_result"},
    {SuiRequiredSignBoundKind::eq, "sui.coin_flow0_asset_state", "proven_sui"},
    {SuiRequiredSignBoundKind::eq, "sui.coin_flow0_amount_known", "yes"},
    {SuiRequiredSignBoundKind::eq, "sui.coin_flow0_sink_kind", "transfer_recipient"},
};
