export type PolicyValueType = "string" | "u64_decimal";
export type SignRuleBoundKind = "eq" | "string" | "string_eq" | "lte";

export interface PolicyFieldDescriptor {
  type: PolicyValueType;
  allowEq: boolean;
  allowIn: boolean;
  allowLte: boolean;
}

export interface SignRuleBound {
  kind: SignRuleBoundKind;
  field: string;
  value?: string;
}

// Generated from specs/sui-sign-transaction-policy-contract.tsv.
// Do not edit by hand. Run npm run generate:sui-policy-contract.
// Firmware remains the signing authority; this is the Core sanitizer projection.
export const COMMON_POLICY_FIELDS: Record<string, PolicyFieldDescriptor> = {
  "common.chain": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "common.method": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "common.intent": { type: "string", allowEq: true, allowIn: true, allowLte: false },
};

export const SUI_SIGN_TRANSACTION_POLICY_FIELDS: Record<string, PolicyFieldDescriptor> = {
  "sui.transaction_kind": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "sui.sender_address": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "sui.gas_owner_address": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "sui.command_count": { type: "u64_decimal", allowEq: true, allowIn: false, allowLte: true },
  "sui.gas_budget": { type: "u64_decimal", allowEq: true, allowIn: false, allowLte: true },
  "sui.gas_price": { type: "u64_decimal", allowEq: true, allowIn: false, allowLte: true },
  "sui.expiration_kind": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "sui.sui_total_out_complete": { type: "string", allowEq: true, allowIn: false, allowLte: false },
  "sui.sui_total_out_raw": { type: "u64_decimal", allowEq: true, allowIn: true, allowLte: true },
  "sui.transfer_total_out_raw": { type: "u64_decimal", allowEq: true, allowIn: true, allowLte: true },
  "sui.move_call_total_in_raw": { type: "u64_decimal", allowEq: true, allowIn: true, allowLte: true },
  "sui.recipient_count": { type: "u64_decimal", allowEq: true, allowIn: true, allowLte: true },
  "sui.recipient0_address": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "sui.recipient0_amount_raw": { type: "u64_decimal", allowEq: true, allowIn: true, allowLte: true },
  "sui.move_call0_package": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "sui.move_call0_module": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "sui.move_call0_function": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "sui.move_call0_sui_amount_raw": { type: "u64_decimal", allowEq: true, allowIn: true, allowLte: true },
  "sui.coin_flow0_source_kind": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "sui.coin_flow0_asset_state": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "sui.coin_flow0_amount_known": { type: "string", allowEq: true, allowIn: false, allowLte: false },
  "sui.coin_flow0_amount_raw": { type: "u64_decimal", allowEq: true, allowIn: true, allowLte: true },
  "sui.coin_flow0_sink_kind": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "sui.coin_flow0_object_id": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "sui.command0_kind": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "sui.command1_kind": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "sui.command2_kind": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "sui.command3_kind": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "sui.command4_kind": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "sui.command5_kind": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "sui.command6_kind": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "sui.command7_kind": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "sui.command0_move_call_package": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "sui.command1_move_call_package": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "sui.command2_move_call_package": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "sui.command3_move_call_package": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "sui.command4_move_call_package": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "sui.command5_move_call_package": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "sui.command6_move_call_package": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "sui.command7_move_call_package": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "sui.command0_move_call_module": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "sui.command1_move_call_module": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "sui.command2_move_call_module": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "sui.command3_move_call_module": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "sui.command4_move_call_module": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "sui.command5_move_call_module": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "sui.command6_move_call_module": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "sui.command7_move_call_module": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "sui.command0_move_call_function": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "sui.command1_move_call_function": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "sui.command2_move_call_function": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "sui.command3_move_call_function": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "sui.command4_move_call_function": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "sui.command5_move_call_function": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "sui.command6_move_call_function": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "sui.command7_move_call_function": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "sui.command0_move_call_type_args": { type: "u64_decimal", allowEq: true, allowIn: false, allowLte: true },
  "sui.command1_move_call_type_args": { type: "u64_decimal", allowEq: true, allowIn: false, allowLte: true },
  "sui.command2_move_call_type_args": { type: "u64_decimal", allowEq: true, allowIn: false, allowLte: true },
  "sui.command3_move_call_type_args": { type: "u64_decimal", allowEq: true, allowIn: false, allowLte: true },
  "sui.command4_move_call_type_args": { type: "u64_decimal", allowEq: true, allowIn: false, allowLte: true },
  "sui.command5_move_call_type_args": { type: "u64_decimal", allowEq: true, allowIn: false, allowLte: true },
  "sui.command6_move_call_type_args": { type: "u64_decimal", allowEq: true, allowIn: false, allowLte: true },
  "sui.command7_move_call_type_args": { type: "u64_decimal", allowEq: true, allowIn: false, allowLte: true },
  "sui.command0_move_call_type_arg0": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "sui.command0_move_call_type_arg1": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "sui.command0_move_call_type_arg2": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "sui.command0_move_call_type_arg3": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "sui.command1_move_call_type_arg0": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "sui.command1_move_call_type_arg1": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "sui.command1_move_call_type_arg2": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "sui.command1_move_call_type_arg3": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "sui.command2_move_call_type_arg0": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "sui.command2_move_call_type_arg1": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "sui.command2_move_call_type_arg2": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "sui.command2_move_call_type_arg3": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "sui.command3_move_call_type_arg0": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "sui.command3_move_call_type_arg1": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "sui.command3_move_call_type_arg2": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "sui.command3_move_call_type_arg3": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "sui.command4_move_call_type_arg0": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "sui.command4_move_call_type_arg1": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "sui.command4_move_call_type_arg2": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "sui.command4_move_call_type_arg3": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "sui.command5_move_call_type_arg0": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "sui.command5_move_call_type_arg1": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "sui.command5_move_call_type_arg2": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "sui.command5_move_call_type_arg3": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "sui.command6_move_call_type_arg0": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "sui.command6_move_call_type_arg1": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "sui.command6_move_call_type_arg2": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "sui.command6_move_call_type_arg3": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "sui.command7_move_call_type_arg0": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "sui.command7_move_call_type_arg1": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "sui.command7_move_call_type_arg2": { type: "string", allowEq: true, allowIn: true, allowLte: false },
  "sui.command7_move_call_type_arg3": { type: "string", allowEq: true, allowIn: true, allowLte: false },
};

export const SUI_CURRENT_SIGN_RULE_BOUNDS: readonly SignRuleBound[] = [
  { kind: "eq", field: "common.chain", value: "sui" },
  { kind: "eq", field: "common.method", value: "sign_transaction" },
  { kind: "eq", field: "common.intent", value: "programmable_transaction" },
  { kind: "eq", field: "sui.transaction_kind", value: "programmable_transaction" },
  { kind: "string", field: "sui.sender_address" },
  { kind: "string", field: "sui.gas_owner_address" },
  { kind: "lte", field: "sui.gas_budget" },
  { kind: "lte", field: "sui.gas_price" },
  { kind: "string", field: "sui.expiration_kind" },
  { kind: "eq", field: "sui.sui_total_out_complete", value: "yes" },
  { kind: "lte", field: "sui.sui_total_out_raw" },
  { kind: "eq", field: "sui.command_count", value: "2" },
  { kind: "eq", field: "sui.command0_kind", value: "split_coins" },
  { kind: "eq", field: "sui.command1_kind", value: "transfer_objects" },
  { kind: "eq", field: "sui.recipient_count", value: "1" },
  { kind: "string_eq", field: "sui.recipient0_address" },
  { kind: "lte", field: "sui.recipient0_amount_raw" },
  { kind: "eq", field: "sui.coin_flow0_source_kind", value: "split_result" },
  { kind: "eq", field: "sui.coin_flow0_asset_state", value: "proven_sui" },
  { kind: "eq", field: "sui.coin_flow0_amount_known", value: "yes" },
  { kind: "eq", field: "sui.coin_flow0_sink_kind", value: "transfer_recipient" },
];
